# Generated by Django 6.0.2 on 2026-03-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_review_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
