# Generated by Django 6.0.2 on 2026-03-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_id'),
        ('product', '0002_alter_product_options_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
